language: python
branches:
  only:
    - main
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install -r maintainers_requirements.txt
script:
  - export PYTHONPATH=`pwd`; cd tests; pytest --cov=hikaru --cov-report=term-missing *.py
after_success:
  - cd tests; curl -s https://codecov.io/bash | bash
