language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install -r maintainers_requirements.txt
env:
  - CODECOV_TOKEN='33edcdbf-2764-465f-86bf-b1866a5dffd7'
script:
  - export PYTHONPATH=`pwd`; cd tests; pytest --cov=hikaru --cov-report=term-missing *.py
after_success:
  - bash < (curl -s https://codecov.io/bash)
